apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::802452485493:role/eksctl-eksctl-demo-nodegroup-ng-8-NodeInstanceRole-1B6BQAKYV3NW7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::802452485493:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-06-17T03:29:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "9602"
  uid: 82907f09-4825-435e-ad74-ffb8277689ab
